/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ca.cityofkingston.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StaffPeople service. Represents a row in the &quot;dir_people&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ca.cityofkingston.model.impl.StaffPeopleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ca.cityofkingston.model.impl.StaffPeopleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StaffPeople
 * @see ca.cityofkingston.model.impl.StaffPeopleImpl
 * @see ca.cityofkingston.model.impl.StaffPeopleModelImpl
 * @generated
 */
@ProviderType
public interface StaffPeopleModel extends BaseModel<StaffPeople> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a staff people model instance should use the {@link StaffPeople} interface instead.
	 */

	/**
	 * Returns the primary key of this staff people.
	 *
	 * @return the primary key of this staff people
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this staff people.
	 *
	 * @param primaryKey the primary key of this staff people
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this staff people.
	 *
	 * @return the ID of this staff people
	 */
	public long getId();

	/**
	 * Sets the ID of this staff people.
	 *
	 * @param id the ID of this staff people
	 */
	public void setId(long id);

	/**
	 * Returns the group of this staff people.
	 *
	 * @return the group of this staff people
	 */
	@AutoEscape
	public String getGroup();

	/**
	 * Sets the group of this staff people.
	 *
	 * @param group the group of this staff people
	 */
	public void setGroup(String group);

	/**
	 * Returns the department of this staff people.
	 *
	 * @return the department of this staff people
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this staff people.
	 *
	 * @param department the department of this staff people
	 */
	public void setDepartment(String department);

	/**
	 * Returns the division of this staff people.
	 *
	 * @return the division of this staff people
	 */
	@AutoEscape
	public String getDivision();

	/**
	 * Sets the division of this staff people.
	 *
	 * @param division the division of this staff people
	 */
	public void setDivision(String division);

	/**
	 * Returns the unit of this staff people.
	 *
	 * @return the unit of this staff people
	 */
	@AutoEscape
	public String getUnit();

	/**
	 * Sets the unit of this staff people.
	 *
	 * @param unit the unit of this staff people
	 */
	public void setUnit(String unit);

	/**
	 * Returns the title of this staff people.
	 *
	 * @return the title of this staff people
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this staff people.
	 *
	 * @param title the title of this staff people
	 */
	public void setTitle(String title);

	/**
	 * Returns the last of this staff people.
	 *
	 * @return the last of this staff people
	 */
	@AutoEscape
	public String getLast();

	/**
	 * Sets the last of this staff people.
	 *
	 * @param last the last of this staff people
	 */
	public void setLast(String last);

	/**
	 * Returns the first of this staff people.
	 *
	 * @return the first of this staff people
	 */
	@AutoEscape
	public String getFirst();

	/**
	 * Sets the first of this staff people.
	 *
	 * @param first the first of this staff people
	 */
	public void setFirst(String first);

	/**
	 * Returns the name of this staff people.
	 *
	 * @return the name of this staff people
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this staff people.
	 *
	 * @param name the name of this staff people
	 */
	public void setName(String name);

	/**
	 * Returns the phone of this staff people.
	 *
	 * @return the phone of this staff people
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this staff people.
	 *
	 * @param phone the phone of this staff people
	 */
	public void setPhone(String phone);

	/**
	 * Returns the fax of this staff people.
	 *
	 * @return the fax of this staff people
	 */
	@AutoEscape
	public String getFax();

	/**
	 * Sets the fax of this staff people.
	 *
	 * @param fax the fax of this staff people
	 */
	public void setFax(String fax);

	/**
	 * Returns the email of this staff people.
	 *
	 * @return the email of this staff people
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this staff people.
	 *
	 * @param email the email of this staff people
	 */
	public void setEmail(String email);

	/**
	 * Returns the tstamp of this staff people.
	 *
	 * @return the tstamp of this staff people
	 */
	public Date getTstamp();

	/**
	 * Sets the tstamp of this staff people.
	 *
	 * @param tstamp the tstamp of this staff people
	 */
	public void setTstamp(Date tstamp);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ca.cityofkingston.model.StaffPeople staffPeople);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ca.cityofkingston.model.StaffPeople> toCacheModel();

	@Override
	public ca.cityofkingston.model.StaffPeople toEscapedModel();

	@Override
	public ca.cityofkingston.model.StaffPeople toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}