package ca.cityofkingston.payments;

import java.util.Date;

public enum ServiceError {
	
	OPERATION_TIMED_OUT, 
	UNHANDLED_EXCEPTION, 
	RESOURCE_CANNOT_BE_FOUND, 
	CONNECT_FAILED, 
	TIMED_OUT, 
	OPERATION_TIMED_OUT_AFTER;

	public String getTemplate(String sourceIp, Date when, String body) {
		
		StringBuilder sb = new StringBuilder();
		
		sb.append("<p>");
		sb.append(getTemplateHeading());
		sb.append("</p>\n");
		sb.append("<p>Date & time of the error was: ").append(when).append("</p>\n");
		sb.append("<p>The Exception Report generated by gBiz is below. (The user has been told to try again.)</p>\n");
		sb.append("<p>User's IP address was: ").append(sourceIp).append("</p>\n");
		sb.append("<p>The response was:<br/>");
		sb.append(body);
		sb.append("<p>");
		
		return sb.toString();
		
	}

	public String getSubject() {
		
		if(this.equals(UNHANDLED_EXCEPTION) || this.equals(RESOURCE_CANNOT_BE_FOUND)) {
			
			return "eCity Payments Error Report: gBiz Exception";
		
		} else if(this.equals(CONNECT_FAILED) || this.equals(TIMED_OUT) || this.equals(OPERATION_TIMED_OUT_AFTER)) {
			
			return "eCity Payments Error Report: Wrapper/gBiz Connect Error";
		}
		
		return "eCity Payments Error Report: Wrapper/gBiz Data-Transfer Error";
	}
	
	private String getTemplateHeading() {
		
		if(this.equals(UNHANDLED_EXCEPTION) || this.equals(RESOURCE_CANNOT_BE_FOUND)) {
			
			return "<strong>gBiz has generated an exception error.</strong>";
		
		} else {
			
			return "<strong>The ESD wrapper on the City website has timed out while receiving a response from the gBiz server.</strong>";
			
		}
	}	

}
